# Generated by Django 4.0.1 on 2022-07-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='address'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='students',
        ),
        migrations.AddField(
            model_name='post',
            name='students',
            field=models.ManyToManyField(null=True, to='User.Student'),
        ),
    ]
