# Generated by Django 4.0.1 on 2022-07-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tags_remove_post_address_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=100, null=True, verbose_name='tags'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
