# Generated by Django 4.0.1 on 2022-07-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_post_tags_post_tags_delete_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
