# Generated by Django 4.0.1 on 2022-07-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_remove_business_posts_post_businesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='gmail_password',
            field=models.CharField(max_length=100, null=True, verbose_name='gmail password'),
        ),
    ]
