# Generated by Django 4.0.1 on 2022-08-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_remove_post_students_post_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='students',
        ),
        migrations.AddField(
            model_name='post',
            name='students',
            field=models.ManyToManyField(null=True, to='User.Student'),
        ),
    ]
