# Generated by Django 4.0.1 on 2022-08-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_remove_post_students_post_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='students',
            field=models.ManyToManyField(null=True, related_name='joined_jobs', to='User.Student'),
        ),
    ]
